### PR TITLE
Replaced "Java Money" with JavaMoney

### PR DESCRIPTION
**Pull request by LappleApple**
This could help with SEO and other matters ... as per https://github.com/JavaMoney

### CODE REVIEW

**Comment by jhorstmann** [comment]
:+1: as the same way of writing is used on http://javamoney.github.io/

**Comment by whiskeysierra** [comment]
:+1+

**Comment by whiskeysierra** [comment]
:+1:

**Comment by whiskeysierra** [comment]
:+1:

**Comment by whiskeysierra** [comment]
+1

**Comment by whiskeysierra** [comment]
:shipit:

**Comment by whiskeysierra** [comment]
LGTM

**Comment by whiskeysierra** [comment]
Zappr is driving me nuts... :rage:

**Pull request merged**
