### PR TITLE
Unifies SECURITY.md to point to the Zalando security form

### PR DESCRIPTION
**Pull request by bocytko**
Unifies SECURITY.md to point to the Zalando security form.

## Motivation and Context
The majority of projects links to the security form. We still have some repositories that point to e-mail boxes.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by whiskeysierra** [comment]
👍

**Comment by whiskeysierra** [comment]
@bocytko Can you rebase onto master? I had to make the coverage step conditional in order not to run for PRs.

**Comment by bocytko** [comment]
@whiskeysierra sure, I just pushed the rebased code.

**Comment by whiskeysierra** [comment]
:+1:

**Comment by whiskeysierra** [comment]
Commit is not signed... 😢

**Comment by bocytko** [comment]
I signed the commit now. Thanks for your patience :)

**Comment by whiskeysierra** [comment]
:+1:

**Pull request merged**
