### PR TITLE
Switched to MIT license

### PR DESCRIPTION
**Pull request by whiskeysierra**

### CODE REVIEW

**Comment by jhorstmann** [comment]
Fine by me, but other contributors should also agree

**Comment by jhorstmann** [comment]
:+1:

**Comment by lukasniemeier-zalando** [comment]
I don't want to wake the dragons, but why do you want to switch now (not that I disagree)?

**Comment by whiskeysierra** [comment]
Basically because I want to have the same license everywhere. For new stuff we use MIT already and for the *older* ones we use Apache. I asked @LappleApple whether I could switch all projects.

**Comment by lukasniemeier-zalando** [comment]
:+1:

**Pull request merged**
